---
abstract: 'Crypt::PBC::WIBE - Wildcarded Identity-based Encryption Scheme'
author:
  - 'Oliver Günther <mail@oliverguenther.de>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.120921'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-PBC-WIBE
requires:
  Carp: 0
  Crypt::PBC: 0
version: 0.1.1
